-- ============================================
-- ADD MISSING COLUMNS TO candidate_profile_scores TABLE
-- Based on PROFILE_TYPE_RULES in profile_type_utils.py
-- ============================================
-- Run this script to add all missing score columns to your candidate_profile_scores table

USE ats_db;

-- ============================================
-- Main Profile Types (25 columns)
-- ============================================
ALTER TABLE candidate_profile_scores 
ADD COLUMN IF NOT EXISTS java_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS dotnet_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS python_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS javascript_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS fullstack_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS devops_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS cloud_infra_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS data_engineering_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS data_science_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS business_intelligence_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS testing_qa_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS sap_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS erp_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS microsoft_power_platform_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS rpa_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS cyber_security_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS mobile_development_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS salesforce_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS low_code_no_code_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS database_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS integration_apis_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS ui_ux_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS support_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS business_development_score DECIMAL(10,2) DEFAULT 0.0;

-- ============================================
-- Additional Profile Types (50+ columns)
-- ============================================
ALTER TABLE candidate_profile_scores 
ADD COLUMN IF NOT EXISTS go_golang_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS ruby_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS php_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS rust_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS scala_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS c_cpp_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS react_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS angular_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS vue_js_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS node_js_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS microservices_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS serverless_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS aws_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS azure_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS gcp_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS kubernetes_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS docker_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS terraform_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS ansible_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS jenkins_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS gitlab_cicd_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS github_actions_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS mongodb_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS postgresql_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS mysql_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS redis_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS elasticsearch_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS apache_kafka_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS apache_spark_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS hadoop_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS machine_learning_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS deep_learning_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS computer_vision_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS nlp_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS blockchain_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS web3_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS iot_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS embedded_systems_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS game_development_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS ar_vr_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS fintech_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS healthcare_it_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS ecommerce_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS content_management_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS video_streaming_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS network_engineering_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS system_administration_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS graphql_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS typescript_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS linux_score DECIMAL(10,2) DEFAULT 0.0;

-- ============================================
-- Programming Languages (Additional 50 columns)
-- ============================================
ALTER TABLE candidate_profile_scores 
ADD COLUMN IF NOT EXISTS swift_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS kotlin_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS perl_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS shell_scripting_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS powershell_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS groovy_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS clojure_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS erlang_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS elixir_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS haskell_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS fsharp_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS vb_net_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS cobol_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS fortran_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS assembly_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS matlab_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS r_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS julia_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS lua_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS dart_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS objective_c_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS delphi_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS pascal_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS ada_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS prolog_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS lisp_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS smalltalk_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS ocaml_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS racket_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS crystal_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS nim_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS zig_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS v_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS d_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS nix_score DECIMAL(10,2) DEFAULT 0.0;

-- ============================================
-- Infrastructure & Cloud Tools
-- ============================================
ALTER TABLE candidate_profile_scores 
ADD COLUMN IF NOT EXISTS terraform_cloud_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS pulumi_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS cloudformation_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS arm_templates_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS bicep_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS cdk_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS serverless_framework_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS sam_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS zappa_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS chalice_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS vercel_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS netlify_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS firebase_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS supabase_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS appwrite_score DECIMAL(10,2) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS hasura_score DECIMAL(10,2) DEFAULT 0.0;

-- ============================================
-- Verify columns were added
-- ============================================
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_DEFAULT,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ats_db'
  AND TABLE_NAME = 'candidate_profile_scores'
  AND COLUMN_NAME LIKE '%_score'
ORDER BY COLUMN_NAME;

-- ============================================
-- Note: MySQL doesn't support "IF NOT EXISTS" for ALTER TABLE ADD COLUMN
-- If you get "Duplicate column name" errors, those columns already exist
-- You can safely ignore those errors or remove those ALTER TABLE statements
-- ============================================

