"""
Script to insert role mappings into Role_Processor table.
This script reads the role mappings and inserts them into the database.
"""

import logging
import os
from role_processor import RoleProcessor

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Database configuration (can be overridden by environment variables)
DB_CONFIG = {
    'host': os.getenv('MYSQLHOST', os.getenv('MYSQL_HOST', 'localhost')),
    'user': os.getenv('MYSQLUSER', os.getenv('MYSQL_USER', 'root')),
    'password': os.getenv('MYSQLPASSWORD', os.getenv('MYSQL_PASSWORD', 'Reset@123')),
    'database': os.getenv('MYSQLDATABASE', os.getenv('MYSQL_DATABASE', 'ats_db')),
    'port': int(os.getenv('MYSQLPORT', os.getenv('MYSQL_PORT', '3306')))
}

# Role mappings data
ROLE_MAPPINGS = [
    ("Software Engineer", "3d pipeline engineer"),
    ("Architect", "contact center solution architect"),
    ("Architect", "embedded software architect"),
    ("Architect", "enterprise architect"),
    ("Architect", "etl informatica technical architect"),
    ("Architect", "iam solution architect"),
    ("Architect", "it iam security solution architect"),
    ("Architect", "it solution architect"),
    ("Architect", "network solution architect"),
    ("Architect", "software architect"),
    ("Architect", "software technical architect"),
    ("Architect", "solution architect"),
    ("Architect", "sr. enterprise architect"),
    ("Architect", "sr. solution architect"),
    ("Architect", "technical solution architect"),
    ("Architect", "windows software architect"),
    ("Software Engineer", "backend api developer"),
    ("Software Engineer", "backend drupal developer"),
    ("Software Engineer", "backend java developer"),
    ("Software Engineer", "sr .net back end developer"),
    ("Software Engineer", "sr backend qa"),
    ("Software Engineer", "sr. Software Engineer"),
    ("Software Engineer", "web backend application developer"),
    ("Software Engineer", "aws cloud engineer"),
    ("Software Engineer", "azure engineer"),
    ("Software Engineer", "cloud engineer"),
    ("Software Engineer", "oracle cloud architect"),
    ("Consultant", "application security consultant"),
    ("Consultant", "ariba contracts consultant"),
    ("Consultant", "business consultant"),
    ("Consultant", "business continuity emergency management consultant"),
    ("Consultant", "business process consultant"),
    ("Consultant", "business systems consultant"),
    ("Consultant", "change management consultant"),
    ("Consultant", "community engagement consultant"),
    ("Consultant", "consultant"),
    ("Consultant", "executive consultant"),
    ("Consultant", "hr business partner consultant"),
    ("Consultant", "hr consultant"),
    ("Consultant", "hr organizational development consultant"),
    ("Consultant", "human resources consultant"),
    ("Consultant", "human resources investigation consultant"),
    ("Consultant", "iam consultant"),
    ("Consultant", "ibm sccd consultant"),
    ("Consultant", "information systems security consultant"),
    ("Consultant", "it disaster recovery consultant"),
    ("Consultant", "management system planning, procurement & implementation consultant"),
    ("Consultant", "maximo techno functional consultant"),
    ("Consultant", "microsoft d365 crm consultant/architect"),
    ("Consultant", "microsoft power platform consultant"),
    ("Consultant", "ms dynamics functional consultant"),
    ("Consultant", "oracle hrms functional consultant"),
    ("Consultant", "org change management consultant"),
    ("Consultant", "organizational development consultant"),
    ("Consultant", "peoplesoft commitment accounting consultant"),
    ("Consultant", "peoplesoft functional consultant"),
    ("Consultant", "peoplesoft hcm consultant"),
    ("Consultant", "process management consultant"),
    ("Consultant", "production support consultant"),
    ("Consultant", "prosci change management consultant"),
    ("Consultant", "sap consultant"),
    ("Consultant", "sap functional consultant"),
    ("Consultant", "sap group reporting consultant"),
    ("Consultant", "sap hana basis consultant"),
    ("Consultant", "sap hybris consultant"),
    ("Consultant", "sap le techno functional consultant"),
    ("Consultant", "sap sd consultant"),
    ("Consultant", "servicenow consultant"),
    ("Consultant", "siebel technical consultant"),
    ("Consultant", "sr dynamics 365 erp consultant"),
    ("Consultant", "sr manhattan consultant"),
    ("Consultant", "sr sap ibp consultant"),
    ("Consultant", "sr tech consultant"),
    ("Consultant", "sr. change management consultant"),
    ("Consultant", "sr. collibra data lineage consultant"),
    ("Consultant", "sr. communications consultant"),
    ("Consultant", "sr. oracle identity and access management technical consultant"),
    ("Consultant", "sr. sap consultant"),
    ("Consultant", "sr. sap functional consultant"),
    ("Consultant", "sr. sap scm consultant"),
    ("Consultant", "sr.financial management consultant"),
    ("Consultant", "sr.hw consultant"),
    ("Consultant", "talent acquisition support consultant"),
    ("Data Analyst", "agile business analyst"),
    ("Data Analyst", "arcos business analyst/sys"),
    ("Data Analyst", "bi business analyst"),
    ("Data Analyst", "busines data analyst"),
    ("Data Analyst", "business analyst/bde"),
    ("Data Analyst", "business data analyst"),
    ("Data Analyst", "business systems data analyst"),
    ("Data Analyst", "data analyst"),
    ("Data Analyst", "data analytics lea"),
    ("Data Analyst", "data analytics manager"),
    ("Data Analyst", "enterprise data analyst"),
    ("Data Analyst", "hr data analyst"),
    ("Data Analyst", "hybris business analyst"),
    ("Data Analyst", "inventory data analyst"),
    ("Data Analyst", "it marketing bi data analyst"),
    ("Data Analyst", "marketing analytics program"),
    ("Data Analyst", "marketplace data analyst"),
    ("Data Analyst", "maximo business analyst"),
    ("Data Analyst", "merchandising data analyst"),
    ("Data Analyst", "net data analyst"),
    ("Data Analyst", "operational data analyst"),
    ("Data Analyst", "operations data analyst"),
    ("Data Analyst", "performance data analyst"),
    ("Data Analyst", "research data analyst"),
    ("Data Analyst", "retail data analyst"),
    ("Data Analyst", "salesforce data analyst"),
    ("Data Analyst", "sql data analyst"),
    ("Data Analyst", "sql server data analyst"),
    ("Data Analyst", "sr data analyst"),
    ("Data Analyst", "sr data analytics developer"),
    ("Data Analyst", "sr sap data analyst"),
    ("Data Analyst", "sr. business data analyst"),
    ("Data Analyst", "sr. data & analytics architect"),
    ("Data Analyst", "sr. data analyst"),
    ("Data Analyst", "sr. data analyst/data"),
    ("Data Analyst", "sr. data analytics engineer"),
    ("Data Analyst", "sw data analyst/"),
    ("Data Analyst", "technical business analyst"),
    ("Analyst", "business analyst"),
    ("Analyst", "business analyst/project"),
    ("Analyst", "edi business analyst"),
    ("Analyst", "informatics business analyst"),
    ("Analyst", "it business analyst"),
    ("Analyst", "peoplesoft hcm business analyst"),
    ("Analyst", "sap business analyst"),
    ("Analyst", "sap hr business analyst"),
    ("Analyst", "sr business analyst"),
    ("Analyst", "sr it business analyst"),
    ("Analyst", "sr. business analyst"),
    ("Analyst", "sr. informatica analytics developer"),
    ("Analyst", "sr. salesforce crm business analyst"),
    ("Analyst", "sr. use case business analyst"),
    ("Analyst", "sr.business analyst"),
    ("Analyst", "techno functional business analyst"),
    ("Analyst", "windchill prod analytics"),
    ("Software Engineer", "aws Software Engineer"),
    ("Software Engineer", "big Software Engineer"),
    ("Software Engineer", "Software Engineer"),
    ("Software Engineer", "Software Engineering"),
    ("Software Engineer", "data platform engineer"),
    ("Software Engineer", "hadoop bigSoftware Engineer"),
    ("Software Engineer", "internal Software Engineer"),
    ("Software Engineer", "ml Software Engineer"),
    ("Software Engineer", "sr big Software Engineer"),
    ("Software Engineer", "sr Software Engineer"),
    ("Software Engineer", "sr. big Software Engineer"),
    ("Software Engineer", "sr. Software Engineer"),
    ("Software Engineer", "sr. Software Engineer,"),
    ("Software Engineer", "Software Engineer"),
    ("Software Engineer", "sr. Software Engineer"),
    ("Database Administrator", "cloud database admin"),
    ("Database Administrator", "database administrator"),
    ("Database Administrator", "dba"),
    ("Database Administrator", "linux database administration & migration specialist"),
    ("Database Administrator", "mysql database administrator"),
    ("Database Administrator", "oracle 12c database administrator"),
    ("Database Administrator", "oracle database administrator"),
    ("Database Administrator", "oracle database engineer"),
    ("Database Administrator", "oracle dba"),
    ("Database Administrator", "postgre sql dba/programmer"),
    ("Database Administrator", "sql dba"),
    ("Database Administrator", "sql server dba"),
    ("Database Administrator", "sr oracle dba"),
    ("Database Administrator", "sr. database administrator"),
    ("Database Administrator", "sr. db2 database administrator"),
    ("Database Administrator", "sr. oracle database administrator"),
    ("Database Administrator", "sr. oracle dba"),
    ("Database Administrator", "sr. snowflake database administrator"),
    ("Database Administrator", "sr.sql database administrator"),
    ("Database Administrator", "sr.sql server dba"),
    ("Database Administrator", "teradata database administrator"),
    ("Database Administrator", "unix database administration & migration specialist"),
    ("Software Engineer", "aws & sysops or Software Engineer"),
    ("Software Engineer", "aws Software Engineer"),
    ("Software Engineer", "cloud infrastructure engineer"),
    ("Software Engineer", "dev ops engineer"),
    ("Software Engineer", "devops application engineer"),
    ("Software Engineer", "devops developer"),
    ("Software Engineer", "Software Engineer"),
    ("Software Engineer", "devops release manager"),
    ("Software Engineer", "infrastructure engineer"),
    ("Software Engineer", "internal Software Engineer"),
    ("Software Engineer", "network infrastructure engineer"),
    ("Software Engineer", "site reliability engineer"),
    ("Software Engineer", "sr azure devops architects"),
    ("Software Engineer", "sr devops release manager"),
    ("Software Engineer", "sr. azure devops architect"),
    ("Software Engineer", "sr. Software Engineer"),
    ("Software Engineer", "sr. site reliability engineer"),
    ("Software Engineer", "sw infrastructure engineer"),
    ("Engineering Manager", "business development manager"),
    ("Engineering Manager", "product development manager"),
    ("Software Engineer", "api & web developer"),
    ("Software Engineer", "asp.net web developer"),
    ("Software Engineer", "asp.net web ui developer"),
    ("Software Engineer", "back end web developer"),
    ("Software Engineer", "backend web developer"),
    ("Software Engineer", "c# .net web developer"),
    ("Software Engineer", "c# web developer"),
    ("Software Engineer", "c#.net application ui developer"),
    ("Software Engineer", "c#.net applications and web developer"),
    ("Software Engineer", "c#.net ui developer"),
    ("Software Engineer", "c#.net web developer"),
    ("Software Engineer", "c#.net web ui developer"),
    ("Software Engineer", "c#asp.net web developer"),
    ("Software Engineer", "c++ gui developer"),
    ("Software Engineer", "coldfusion web developer"),
    ("Software Engineer", "drupal web developer"),
    ("Software Engineer", "front end developer"),
    ("Software Engineer", "front end java developer"),
    ("Software Engineer", "front end react developer"),
    ("Software Engineer", "front end web developer"),
    ("Software Engineer", "gui developer"),
    ("Software Engineer", "hybris ui developer"),
    ("Software Engineer", "intermediate java web developer"),
    ("Software Engineer", "j2ee java web developer"),
    ("Software Engineer", "j2ee web developer"),
    ("Software Engineer", "java gui developer"),
    ("Software Engineer", "java web developer"),
    ("Software Engineer", "javascript web developer"),
    ("Software Engineer", "mobile front end web developer"),
    ("Software Engineer", "net web developer"),
    ("Software Engineer", "net web ui developer"),
    ("Software Engineer", "open source web developer"),
    ("Software Engineer", "php web developer"),
    ("Software Engineer", "python web developer"),
    ("Software Engineer", "ruby on rails web developer"),
    ("Software Engineer", "sharepoint web developer"),
    ("Software Engineer", "sql web developer"),
    ("Software Engineer", "sr .net web developer"),
    ("Software Engineer", "sr sw web developer"),
    ("Software Engineer", "sr web ui developer"),
    ("Software Engineer", "sr. .net web developer"),
    ("Software Engineer", "sr. asp.net web developer"),
    ("Software Engineer", "sr. c# web developer"),
    ("Software Engineer", "sr. c#.net web developer"),
    ("Software Engineer", "sr. front end developer"),
    ("Software Engineer", "sr. front end java ui developer"),
    ("Software Engineer", "sr. front end ui developer"),
    ("Software Engineer", "sr. Software Engineer"),
    ("Software Engineer", "sr. j2ee web developer"),
    ("Software Engineer", "sr. java ui developer"),
    ("Software Engineer", "sr. java web developer"),
    ("Software Engineer", "sr. php web developer"),
    ("Software Engineer", "sr. software web developer"),
    ("Software Engineer", "sr. web developer"),
    ("Software Engineer", "sr.web developer"),
    ("Software Engineer", "sw backend web developer"),
    ("Software Engineer", "tech writer/web developer/tester"),
    ("Software Engineer", "ui developer"),
    ("Software Engineer", "vb.net web developer"),
    ("Software Engineer", "web developer"),
    ("Software Engineer", "web ui developer"),
    ("Software Engineer", "full stack .net developer"),
    ("Software Engineer", "full stack application, database and etl developer"),
    ("Software Engineer", "full stack back end developer"),
    ("Software Engineer", "Software Engineer"),
    ("Software Engineer", "full stack engineer"),
    ("Software Engineer", "full stack java developer"),
    ("Software Engineer", "fullstack .net developer"),
    ("Software Engineer", "fullstack engineer"),
    ("Software Engineer", "java Software Engineer"),
    ("Software Engineer", "java fullstack developer"),
    ("Software Engineer", "net Software Engineer"),
    ("Software Engineer", "net full stack lead"),
    ("Architect", "net fullstack architect/lea"),
    ("Software Engineer", "net fullstack developer"),
    ("Software Engineer", "sr python Software Engineer"),
    ("Software Engineer", "sr. full stack aws developer"),
    ("Architect", "sr. full stack engineer/architect"),
    ("Architect", "sr. full stack engineer/architect1"),
    ("Software Engineer", "sr. fullstack developer"),
    ("Software Engineer", "sr. fullstack engineer"),
    ("Software Engineer", "sr. fullstack web developer"),
    ("Software Engineer", "sr. java Software Engineer"),
    ("Software Engineer", "android developer"),
    ("Software Engineer", "android developers"),
    ("Software Engineer", "c++/java android developer"),
    ("Software Engineer", "ios and android developer"),
    ("Software Engineer", "ios developer"),
    ("Software Engineer", "ios developers"),
    ("Software Engineer", "iosdeveloper"),
    ("Software Engineer", "jr. wireless Software Engineer"),
    ("Software Engineer", "Software Engineer"),
    ("Software Engineer", "sr android developer"),
    ("Software Engineer", "sr. android developer"),
    ("Software Engineer", "sr. ios developer"),
    ("Software Engineer", "sr. Software Engineer"),
    ("Software Engineer", "azure network administrators"),
    ("Software Engineer", "cisco Software Engineer"),
    ("Software Engineer", "linux Software Engineer"),
    ("Software Engineer", "network admin"),
    ("Software Engineer", "network administrator"),
    ("Software Engineer", "Software Engineer"),
    ("Software Engineer", "sr Software Engineer"),
    ("Software Engineer", "sr. Software Engineer"),
    ("Software Engineer", "sr.Software Engineer"),
    ("Software Engineer", "wireless Software Engineer"),
    ("Product Manager", "ca clarify ppm consultant"),
    ("Product Manager", "digital product manager"),
    ("Product Manager", "ibm bpm developer"),
    ("Product Manager", "product manager"),
    ("Product Manager", "sdpm project coordinator"),
    ("Product Manager", "sr product manager"),
    ("Product Manager", "sr. bpm consultant/trainer"),
    ("Product Manager", "sr. product manager"),
    ("Product Manager", "sr. technical product manager"),
    ("Product Manager", "technical product manager"),
    ("Product Manager", "technology product manager"),
    ("Project Manager", "agile it project manager"),
    ("Project Manager", "ai program manager"),
    ("Project Manager", "amr/ami project manager"),
    ("Project Manager", "assistant project manager"),
    ("Project Manager", "associate project manager"),
    ("Project Manager", "business project manager"),
    ("Project Manager", "communications project manager"),
    ("Project Manager", "construction project manager"),
    ("Project Manager", "corporate communications project manager"),
    ("Project Manager", "digital marketing & media project manager"),
    ("Project Manager", "digital marketing project manager"),
    ("Project Manager", "ems upgrade project manager"),
    ("Program Manager", "ev program manager"),
    ("Project Manager", "healthcare project manager"),
    ("Project Manager", "information security project manager"),
    ("Project Manager", "infrastructure project manager"),
    ("Project Manager", "it infrastructure project manager"),
    ("ProgramManager", "it program manager"),
    ("Project Manager", "it project manager"),
    ("Project Manager", "it project manager,"),
    ("Jr Project Manager", "jr. project manager"),
    ("Program Manager", "logistics program manager"),
    ("Project Manager", "marketing project manager"),
    ("Project Manager", "marketing project manager/producer"),
    ("ProgramManager", "material program manager"),
    ("Project Manager", "organizational development project manager"),
    ("Project Manager", "part time project manager"),
    ("Project Manager", "peoplesoft project manager"),
    ("Project Manager", "planning project manager"),
    ("Project Manager", "privacy project manager"),
    ("Project Manager", "product project manager"),
    ("Project Manager", "program & project manager"),
    ("program manager", "program manager"),
    ("Project Manager", "program manager/director"),
    ("Project Manager", "project manager"),
    ("Project Manager", "project manager/administrator"),
    ("Project Manager", "project manager/program"),
    ("Project Manager", "project manager/systems"),
    ("Project Manager", "project/program manager"),
    ("Project Manager", "qa project manager"),
    ("Project Manager", "retail project manager"),
    ("Program Manager", "sap program manager"),
    ("Program Manager", "sap service management program manager"),
    ("Project Manager", "secops project manager"),
    ("Project Manager", "sharepoint 2010 project manager"),
    ("Project Manager", "sharepoint technical project manager"),
    ("Project Manager", "software release project manager"),
    ("Project Manager", "sr cloud finops project manager"),
    ("ProgramManager", "sr cybersecurity program manager"),
    ("Project Manager", "sr it project manager"),
    ("Program Manager", "sr program manager"),
    ("Project Manager", "sr project manager"),
    ("Project Manager", "sr. hr project manager"),
    ("Project Manager", "sr. infrastructure project manager"),
    ("Program Manager", "sr. it program manager"),
    ("Project Manager", "sr. it project manager"),
    ("Program Manager", "sr. program manager"),
    ("Project Manager", "sr. project manager"),
    ("Project Manager", "sr. technical program manager"),
    ("Project Manager", "sr.project manager"),
    ("Program Manager", "strategic program manager"),
    ("Project Manager", "sw driver development project manager"),
    ("Project Manager", "technical program manager"),
    ("Project Manager", "technical project manager"),
    ("Software Engineer", "android mobile automation test engineer"),
    ("Software Engineer", "android Software Engineer"),
    ("Software Engineer", "android sw test engineer"),
    ("Software Engineer", "automation Software Engineer"),
    ("Software Engineer", "automation sw Software Engineer"),
    ("Software Engineer", "automation test engineer"),
    ("Software Engineer", "bi Software Engineer"),
    ("Software Engineer", "bios test engineer"),
    ("Software Engineer", "database test engineer"),
    ("Software Engineer", "firmware test engineer"),
    ("Software Engineer", "fw/sw dev storage test engineer"),
    ("Software Engineer", "hardware test engineer"),
    ("Software Engineer", "hw test engineer"),
    ("Software Engineer", "iam Software Engineer"),
    ("Software Engineer", "image quality test engineer"),
    ("Software Engineer", "image test engineer"),
    ("Software Engineer", "infrastructure qa test engineer"),
    ("Software Engineer", "infrastructure test engineer"),
    ("Software Engineer", "ios mobile automation test engineer"),
    ("Software Engineer", "jr. software tester"),
    ("Software Engineer", "linux Software Engineer"),
    ("Software Engineer", "linux test engineer"),
    ("Software Engineer", "mainframes test engineer"),
    ("Software Engineer", "mobile automation test engineer"),
    ("Software Engineer", "mobile Software Engineer"),
    ("Software Engineer", "mobile quality assurance"),
    ("Software Engineer", "multimedia test engineer"),
    ("Software Engineer", "net Software Engineer"),
    ("Software Engineer", "network driver test engineer"),
    ("Software Engineer", "network test engineer"),
    ("Software Engineer", "oracle apps test engineer"),
    ("Software Engineer", "pc application test engineer"),
    ("Software Engineer", "performance test engineer"),
    ("Software Engineer", "product test engineer"),
    ("Software Engineer", "Software Engineer"),
    ("Software Engineer", "qa test engineer"),
    ("Software Engineer", "quality assurance analyst"),
    ("Software Engineer", "quality assurance engineer"),
    ("Software Engineer", "quality assurance lea"),
    ("Software Engineer", "quality assurance tester"),
    ("Software Engineer", "s/w quality assurance engineer"),
    ("Software Engineer", "sap mm test engineer"),
    ("Software Engineer", "sap performance test engineer"),
    ("Software Engineer", "sdet consultant"),
    ("Software Engineer", "section 508 test engineer"),
    ("Software Engineer", "software application tester"),
    ("Software Engineer", "software network test"),
    ("Software Engineer", "software Software Engineer"),
    ("Software Engineer", "software quality assurance analyst"),
    ("Software Engineer", "software test development engineer"),
    ("Software Engineer", "software test engineer"),
    ("Software Engineer", "software test technician"),
    ("Software Engineer", "software tester"),
    ("Software Engineer", "software validation test engineer"),
    ("Software Engineer", "sr automation Software Engineer"),
    ("Software Engineer", "sr Software Engineer"),
    ("Software Engineer", "sr quality assurance"),
    ("Software Engineer", "sr quality assurance manager"),
    ("Software Engineer", "sr test engineer"),
    ("Software Engineer", "sr. automation test engineer"),
    ("Software Engineer", "sr. etl test engineer"),
    ("Software Engineer", "sr. qa automation/performance test engineer"),
    ("Software Engineer", "sr. quality assurance"),
    ("Software Engineer", "sr. software Software Engineer"),
    ("Software Engineer", "sr.Software Engineer"),
    ("Software Engineer", "sr.qa test engineer"),
    ("Software Engineer", "sw automation Software Engineer"),
    ("Software Engineer", "sw automation test engineer"),
    ("Software Engineer", "sw localization test engineer"),
    ("Software Engineer", "sw product Software Engineer"),
    ("Software Engineer", "sw Software Engineer"),
    ("Software Engineer", "sw test engineer"),
    ("Software Engineer", "sw test engineering"),
    ("Software Engineer", "systems test engineer"),
    ("Software Engineer", "test engineer"),
    ("Software Engineer", "uat test engineer"),
    ("Software Engineer", "web Software Engineer"),
    ("Software Engineer", "windows systems test engineer"),
    ("Software Engineer", "certified network Software Engineer"),
    ("Software Engineer", "cyber security analyst"),
    ("Software Engineer", "cyberSoftware Engineer"),
    ("Software Engineer", "data security analyst"),
    ("Software Engineer", "information security analyst"),
    ("Software Engineer", "information Software Engineer"),
    ("Analyst", "it security analyst"),
    ("Software Engineer", "ms exchange Software Engineer"),
    ("Software Engineer", "network security analyst"),
    ("Software Engineer", "network Software Engineer"),
    ("Software Engineer", "pci compliance/security analyst"),
    ("Software Engineer", "purview Software Engineer"),
    ("Software Engineer", "Software Engineer"),
    ("Software Engineer", "sr. data security analyst"),
    ("Software Engineer", "sr. information security analyst"),
    ("Software Engineer", "sr. information Software Engineer"),
    ("Analyst", "sr. it security analyst"),
    ("Analyst", "sr. network security analyst"),
    ("Software Engineer", "sr. network Software Engineer"),
    ("Analyst", "sr. security analyst"),
    ("Software Engineer", "analytical software engineer"),
    ("Software Engineer", "android software engineer"),
    ("Software Engineer", "android sw engineer"),
    ("Software Engineer", "asp. net sw engineer"),
    ("Software Engineer", "backend software engineer"),
    ("Software Engineer", "build sw engineer"),
    ("Software Engineer", "c / c++ android software engineer"),
    ("Software Engineer", "c / c++ sw engineer"),
    ("Software Engineer", "c#.net software engineer"),
    ("Software Engineer", "c#.net sw engineer"),
    ("Software Engineer", "c++ embedded software engineer"),
    ("Software Engineer", "c++ embedded sw engineer"),
    ("Software Engineer", "c++ software developer"),
    ("Software Engineer", "c++ software engineer"),
    ("Software Engineer", "c++ sw engineer"),
    ("Software Engineer", "c++/c# sw engineer"),
    ("Software Engineer", "c++graphics software engineer"),
    ("Software Engineer", "c, c++ software developer"),
    ("Software Engineer", "c, c++ software engineer"),
    ("Software Engineer", "c/c++ software developer"),
    ("Software Engineer", "c/c++ software engineer"),
]


def main():
    """Main function to insert role mappings."""
    logger.info("Starting role mapping insertion...")
    logger.info(f"Connecting to database: {DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['database']}")
    
    try:
        with RoleProcessor(config=DB_CONFIG) as rp:
            # Bulk insert all mappings
            inserted_count = rp.bulk_insert_role_mappings(ROLE_MAPPINGS)
            
            logger.info(f"Successfully inserted {inserted_count} role mappings")
            
            # Display summary statistics
            all_normalized = rp.get_all_normalized_roles()
            logger.info(f"\nTotal normalized roles: {len(all_normalized)}")
            logger.info(f"Normalized roles: {', '.join(sorted(all_normalized))}")
            
            # Show some examples
            logger.info("\nExample mappings:")
            for normalized_role in sorted(all_normalized)[:5]:  # Show first 5
                original_roles = rp.get_all_original_roles(normalized_role)
                logger.info(f"\n{normalized_role} ({len(original_roles)} original roles):")
                for orig in original_roles[:5]:  # Show first 5 original roles
                    logger.info(f"  - {orig}")
                if len(original_roles) > 5:
                    logger.info(f"  ... and {len(original_roles) - 5} more")
            
    except Exception as e:
        logger.error(f"Error inserting role mappings: {e}", exc_info=True)
        return 1
    
    logger.info("\nRole mapping insertion completed successfully!")
    return 0


if __name__ == "__main__":
    exit(main())

